/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'root' at '2/9/17 8:28 PM' with Gradle 3.2.1
 *
 * @author root, @date 2/9/17 8:28 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
